# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: github
      revision: eb189d59674bc4b2b4bc879d69db1acee0dfc855
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: github
      revision: e6d0be29c417f5874dcba785f45cea38f4200701
      path: middlewares/cerberus
    - name: mcuboot
      remote: github
      revision: c866f5b3479cadeef0ce4d02832080af66b04dd3
      path: bootloader/mcuboot
