# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: gerrit
      url-base: ssh://gerrit.aspeed.com:29418
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: gerrit
      revision: e2f01b0581f8ea62b68b93924ef35c48031d5f7e
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: gerrit
      revision: 928023afa90bd0c50ed7578e573b4daabef09a23
      path: middlewares/cerberus
    - name: mcuboot
      remote: gerrit
      revision: 5bb9418452187b51b8f7d96c5df9c265f7aae9eb
      path: bootloader/mcuboot
