# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: gerrit
      url-base: ssh://gerrit.aspeed.com:29418
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: gerrit
      revision: eb189d59674bc4b2b4bc879d69db1acee0dfc855
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: gerrit
      revision: aspeed-dev
      path: middlewares/cerberus
    - name: mcuboot
      remote: gerrit
      revision: aspeed-dev-v2.6.0
      path: bootloader/mcuboot
