# Copyright (c) 2022 ASPEED Technology Inc.
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: aspeed-zephyr-project

  remotes:
    - name: github
      url-base: https://github.com/AspeedTech-BMC

  projects:
    - name: zephyr
      remote: github
      revision: cfe94dc149ffa0af7e1af668a27f57eecf0cd1e9
      import:
        name-whitelist:
          - mcumgr
          - cmsis
          - mcuboot
          - mbedtls
    - name: cerberus
      remote: github
      revision: 928023afa90bd0c50ed7578e573b4daabef09a23
      path: middlewares/cerberus
    - name: mcuboot
      remote: github
      revision: a28491529cbd9fcdde441fe1f1aa9e257042fe30
      path: bootloader/mcuboot
