/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (c) 2026 ASPEED Technology Inc.
 *
 * Generated by tools/certs/gen_ca_certs.py. Do not edit by hand;
 * regenerate from the .crt/.cer inputs instead.
 */

#pragma once

#include <stdint.h>

struct cptra_ca_cert {
	const uint8_t *der;
	uint32_t len;
	const char *name;
};

extern const uint8_t cptra_aspeed_root_ca_der[];
extern const uint32_t cptra_aspeed_root_ca_der_len;

/* Peer sub CAs; the one that issued this part's IDevID is
 * selected at run time by cptra_load_certificate().
 */
extern const struct cptra_ca_cert cptra_aspeed_sub_ca[];
extern const uint32_t cptra_aspeed_sub_ca_count;
extern const uint8_t cptra_aspeed_sub_ca0_der[];
extern const uint32_t cptra_aspeed_sub_ca0_der_len;
extern const uint8_t cptra_aspeed_sub_ca1_der[];
extern const uint32_t cptra_aspeed_sub_ca1_der_len;
