/*
 * Copyright (c) 2026 ASPEED Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef _MAC_AST2700_H
#define _MAC_AST2700_H

#include <chip.h>

#define ASPEED_IO_MAC0_BASE	0x14050000UL
#define ASPEED_IO_MAC1_BASE	0x14060000UL

#define IER			0x04
#define TXPD			0x18
#define TXR_BADR		0x20
#define RXR_BADR		0x24
#define APTC			0x34
#define APTC_RPOLL_CNT		GENMASK(3, 0)
#define DBLAC			0x38
#define DBLAC_RDES_SIZE(x)	(((x) & 0xf) << 12)
#define DBLAC_TDES_SIZE(x)	(((x) & 0xf) << 16)
#define DBLAC_DESC_UINT		8
#define FEAR			0x40
#define RBSR			0x4c
#define MACCR			0x50
#define MACCR_TXDMA_EN		BIT(0)
#define MACCR_RXDMA_EN		BIT(1)
#define MACCR_TXMAC_EN		BIT(2)
#define MACCR_RXMAC_EN		BIT(3)
#define MACCR_FULLDUP		BIT(8)
#define MACCR_GMAC_MODE		BIT(9)
#define MACCR_CRC_APD		BIT(10)
#define MACCR_RX_RUNT		BIT(12)
#define MACCR_RX_BROADPKT_EN	BIT(17)

#define TXR_BADR_HI		0x17c
#define RXR_BADR_HI		0x18c

#define MAC_TXDES0_TXDMA_OWN	BIT(31)
#define MAC_TXDES0_EDOTR	BIT(30)
#define MAC_TXDES0_FTS		BIT(29)
#define MAC_TXDES0_LTS		BIT(28)
#define MAC_TXDES0_TXBUF_SIZE(x)	((x) & 0x3fff)

#define MAC_TXDES2_TXBUF_BADR_HI	GENMASK(18, 16)

#define MAC_RXDES0_RXPKT_RDY	BIT(31)
#define MAC_RXDES0_EDORR	BIT(30)
#define MAC_RXDES0_RX_ODD_NB	BIT(22)
#define MAC_RXDES0_RUNT	BIT(21)
#define MAC_RXDES0_FTL		BIT(20)
#define MAC_RXDES0_CRC_ERR	BIT(19)
#define MAC_RXDES0_RX_ERR	BIT(18)

#define MAC_RXDES0_ANY_ERROR \
	(MAC_RXDES0_RX_ERR | MAC_RXDES0_CRC_ERR | MAC_RXDES0_FTL | \
	 MAC_RXDES0_RUNT | MAC_RXDES0_RX_ODD_NB)

#define MAC_RXDES2_RXBUF_BADR_HI	GENMASK(18, 16)

#define MAC_TX_POLL_INTERVAL_US	10
#define MAC_TX_TIMEOUT_US	10000

#define TX_DELAY_1		GENMASK(5, 0)
#define TX_DELAY_2		GENMASK(11, 6)
#define RX_DELAY_1		GENMASK(17, 12)
#define RX_DELAY_2		GENMASK(23, 18)

#define SCU_HW_REVISION_ID	GENMASK(23, 16)
#define SCU_FREQ_RING_ENABLE	BIT(0)
#define SCU_FREQ_OSC_ENABLE	BIT(1)
#define SCU_FREQ_SELECT_DLY32	FIELD_PREP(GENMASK(5, 2), 0x5)
#define SCU_FREQ_SELECT_RGMII	FIELD_PREP(GENMASK(5, 2), 0xd)
#define SCU_FREQ_DONE		BIT(6)
#define SCU_FREQ_RING_STG(x)	FIELD_PREP(GENMASK(14, 9), (x))
#define SCU_FREQ_COUNTER_MASK	GENMASK(29, 16)
#define SCU_FREQ_COUNTER(x)	FIELD_GET(SCU_FREQ_COUNTER_MASK, (x))

#define SCU_DBGSEL_RING_SEL_MASK	GENMASK(15, 8)
#define SCU_DBGSEL_RING_SEL(x)		FIELD_PREP(SCU_DBGSEL_RING_SEL_MASK, (x))
#define SCU_DBGSEL_RING_SEL_RGMII0_TX	44
#define SCU_DBGSEL_RING_SEL_RGMII1_TX	45
#define SCU_DBGSEL_RING_SEL_RGMII0_RX	46
#define SCU_DBGSEL_RING_SEL_RGMII1_RX	47

#define SCU_CLK_SEL1_RGMIICLK		0x06000000
#define SCU_CLK_SEL1_RGMIICLK_MASK	GENMASK(27, 25)
#define SCU_CLK_SEL1_RMHCLK		0x80000000
#define SCU_CLK_SEL1_MHCLK_MASK		GENMASK(31, 29)

#define SCU_MULTI_CTRL18	0x444
#define SCU_MULTI_CTRL19	0x448
#define SCU_MULTI_CTRL20	0x44c
#define SCU_MULTI_CTRL21	0x450

#define SCU1_SCRATCH_TX_DELAY_STEP(x)	FIELD_PREP(GENMASK(15, 0), (x))
#define SCU1_SCRATCH_RX_DELAY_STEP(x)	FIELD_PREP(GENMASK(31, 16), (x))

#define MAC_DESC_ALIGN		64

int mac_init(struct ast_chip *chip);

#endif
