#define MBEDTLS_BASE64_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_USE_C

#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CSR_WRITE_C
#define MBEDTLS_PEM_WRITE_C

#define MBEDTLS_ECP_RESTARTABLE
#define MBEDTLS_HKDF_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_AES_FEWER_TABLES

#define MBEDTLS_GCM_C
#define MBEDTLS_AES_C

/* MBEDTLS_SHA512_SMALLER trades SHA-512 speed for code size. Disabled on
 * AST1080 (CONFIG_SOC_AST1080_CM4); still enabled for all other boards. */
#ifndef CONFIG_SOC_AST1080_CM4
#define MBEDTLS_SHA512_SMALLER
#endif
//#define MBEDTLS_LMS_C
//#define MBEDTLS_LMS_PRIVATE
