# nothing here
CONFIG_ASPEED_DDR_3200=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_CPTRA_MANIFEST=y
CONFIG_CPTRA_MANIFEST_SIGNATURE=y
CONFIG_CRC=y
CONFIG_UART_CONSOLE=y
CONFIG_RESET=y
CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_SPI_NOR_MULTI_DEV=y
# TODO: move CONFIG_SPI_ASPEED_AST2700 to <Board>.conf after SPI driver for AST1040 ready
CONFIG_SPI_ASPEED_AST2700=y
CONFIG_SPI_DMA_SUPPORT_ASPEED=y
CONFIG_FLASH_PAGE_LAYOUT=y
# CONFIG_SPI_NOR is not set
CONFIG_FLASH_MAP=y
CONFIG_WATCHDOG=y
CONFIG_WDT_ASPEED_G7=y
CONFIG_HEAP_MEM_POOL_SIZE=500
CONFIG_LOG=y
