#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2026 ASPEED Technology Inc.
#
# Convert the ASPEED CA certificates to DER and emit the C arrays that
# cptra_api.c preloads into the Caliptra certificate cache.
#
# Usage:
#   tools/certs/gen_ca_certs.py \
#       --root src/cptra/ASPEED_CA.crt \
#       --sub  src/cptra/AST27x0_ECDSA0.cer \
#       --sub  src/cptra/AST27x0_ECDSA1.cer \
#       --outdir src/cptra
#
# --sub may be repeated; the sub CAs are emitted as a table and the one that
# issued this part's IDevID is picked at run time. Inputs may be PEM or DER,
# with or without a text preamble ahead of the PEM block.

import argparse
import base64
import os
import re
import sys

PEM_RE = re.compile(
    rb"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", re.DOTALL)

HEADER = ("/*\n"
          " * SPDX-License-Identifier: Apache-2.0\n"
          " *\n"
          " * Copyright (c) 2026 ASPEED Technology Inc.\n"
          " *\n"
          " * Generated by tools/certs/gen_ca_certs.py. Do not edit by hand;\n"
          " * regenerate from the .crt/.cer inputs instead.\n"
          " */\n\n")


def to_der(path):
    """Return DER bytes for a PEM or DER encoded certificate."""
    with open(path, "rb") as handle:
        raw = handle.read()

    match = PEM_RE.search(raw)
    if match:
        der = base64.b64decode(re.sub(rb"\s+", b"", match.group(1)))
    else:
        der = raw

    if not der.startswith(b"\x30"):
        sys.exit("%s: not a DER SEQUENCE, is this a certificate?" % path)
    return der


def c_array(der):
    lines = []
    for offset in range(0, len(der), 12):
        chunk = der[offset:offset + 12]
        lines.append("\t" + " ".join("0x%02x," % b for b in chunk))
    return "\n".join(lines)


def emit_cert(handle, symbol, path, der):
    handle.write("\n/* %s */\n" % (os.path.basename(path) if path else "not provided"))
    handle.write("const uint8_t %s[] = {\n" % symbol)
    # A zero-length array is a GNU extension; emit a single pad byte and
    # carry the real length separately so the slot stays unpopulated.
    handle.write(c_array(der if der else b"\x00") + "\n")
    handle.write("};\n")
    handle.write("const uint32_t %s_len = %d;\n" % (symbol, len(der)))


def convert(path):
    der = to_der(path)
    der_path = os.path.splitext(path)[0] + ".der"
    with open(der_path, "wb") as handle:
        handle.write(der)
    print("%s -> %s (%d bytes)" % (path, der_path, len(der)))
    return der


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", help="ASPEED root CA certificate (PEM or DER)")
    parser.add_argument("--sub", action="append", default=[],
                        help="ASPEED sub CA certificate; may be repeated")
    parser.add_argument("--outdir", required=True)
    args = parser.parse_args()

    root_der = convert(args.root) if args.root else b""
    if not args.root:
        print("root CA: no input, emitting empty array")

    subs = [(path, convert(path)) for path in args.sub]

    source = os.path.join(args.outdir, "cptra_ca_certs.c")
    with open(source, "w") as handle:
        handle.write(HEADER)
        handle.write('#include "cptra_ca_certs.h"\n')

        emit_cert(handle, "cptra_aspeed_root_ca_der", args.root, root_der)

        for index, (path, der) in enumerate(subs):
            emit_cert(handle, "cptra_aspeed_sub_ca%d_der" % index, path, der)

        handle.write("\nconst struct cptra_ca_cert cptra_aspeed_sub_ca[] = {\n")
        for index, (path, _) in enumerate(subs):
            name = os.path.splitext(os.path.basename(path))[0]
            handle.write('\t{ cptra_aspeed_sub_ca%d_der, cptra_aspeed_sub_ca%d_der_len, "%s" },\n'
                         % (index, index, name))
        handle.write("};\n")
        handle.write("const uint32_t cptra_aspeed_sub_ca_count = %d;\n" % len(subs))

    header = os.path.join(args.outdir, "cptra_ca_certs.h")
    with open(header, "w") as handle:
        handle.write(HEADER)
        handle.write("#pragma once\n\n"
                     "#include <stdint.h>\n\n"
                     "struct cptra_ca_cert {\n"
                     "\tconst uint8_t *der;\n"
                     "\tuint32_t len;\n"
                     "\tconst char *name;\n"
                     "};\n\n"
                     "extern const uint8_t cptra_aspeed_root_ca_der[];\n"
                     "extern const uint32_t cptra_aspeed_root_ca_der_len;\n\n"
                     "/* Peer sub CAs; the one that issued this part's IDevID is\n"
                     " * selected at run time by cptra_load_certificate().\n"
                     " */\n"
                     "extern const struct cptra_ca_cert cptra_aspeed_sub_ca[];\n"
                     "extern const uint32_t cptra_aspeed_sub_ca_count;\n")
        for index in range(len(subs)):
            handle.write("extern const uint8_t cptra_aspeed_sub_ca%d_der[];\n" % index)
            handle.write("extern const uint32_t cptra_aspeed_sub_ca%d_der_len;\n" % index)

    print("wrote %s and %s" % (source, header))


if __name__ == "__main__":
    main()
